package Exception;

public class Demo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("Output: ");
try 
{
	int a=10, b=20,c=30;
	System.out.println("C= "+c);
}
catch (ArithmeticException a)
{
	System.out.println(a);
}
	}

}

